name: Build, publish and deploy to MonsterASP.NET
on: [push]

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish --runtime win-x86 
        
      - name: Test with .NET
        run: dotnet test

      - name: Install Web Deploy
        run: choco install webdeploy --yes --no-progress

      - name: Deploy to MonsterASP.NET via WebDeploy
        run: |
          $msdeploy = "$env:ProgramFiles\IIS\Microsoft Web Deploy V3\msdeploy.exe"
          $computerName = "https://${{ secrets.SERVER_COMPUTER_NAME }}:8172/msdeploy.axd?site=${{ secrets.WEBSITE_NAME }}"
          & $msdeploy -verb:sync "-source:contentPath=.\publish" "-dest:contentPath=${{ secrets.WEBSITE_NAME }},computerName=$computerName,userName=${{ secrets.SERVER_USERNAME }},password=${{ secrets.SERVER_PASSWORD }},authtype=Basic" -allowUntrusted
