name: Build, publish and deploy to MonsterASP.NET
on: [push]

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish --runtime win-x86 
        
      - name: Test with .NET
        run: dotnet test

      - name: Install Web Deploy
        run: choco install webdeploy --yes --no-progress

      - name: Deploy to MonsterASP.NET via WebDeploy
        env:
          WEBSITE_NAME: ${{ secrets.WEBSITE_NAME }}
          SERVER_COMPUTER_NAME: ${{ secrets.SERVER_COMPUTER_NAME }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          $msdeploy = "$env:ProgramFiles\IIS\Microsoft Web Deploy V3\msdeploy.exe"
          $computerName = "https://$env:SERVER_COMPUTER_NAME:8172/msdeploy.axd?site=$env:WEBSITE_NAME"
          $dest = "contentPath=$env:WEBSITE_NAME,computerName=$computerName,userName=$env:SERVER_USERNAME,password=$env:SERVER_PASSWORD,authtype=Basic"
          & $msdeploy -verb:sync "-source:contentPath=.\publish" "-dest:$dest" -allowUntrusted
